### ISSUE TITLE
Automatic Publishing

### ISSUE THREAD

**Issue by seveibar** [seamapi/python-legacy#13]
1. Increment pyproject.toml version
2. Run `poetry build`
3. Run `poetry publish`

PyPi credentials will be needed

Is there a github action that will handle publishing? Do we need to commit back to the repo for the version update?

**Comment by codetheweb** [comment]
Closed by https://github.com/seamapi/python/commit/5fd13f5d3b941a3118345a98aa7deed54b10039a.
