### ISSUE TITLE
Getting a 500 on https://ghcr.io/v2/seamapi/seam-connect/manifests/latest when running tests

### ISSUE THREAD

**Issue by hernan-erasmo** [seamapi/python-legacy#68]
As the title says, when I follow the [instructions for running the tests](https://github.com/seamapi/python/tree/65aa17f434761164d26a1b7f8ec1e00e6e73170d#development) and try to run

`poetry run pytest -s ./tests/test_init_seam.py`

I keep getting the following error message

`docker.errors.APIError: 500 Server Error for http+docker://localnpipe/v1.41/images/create?tag=latest&fromImage=ghcr.io%2Fseamapi%2Fseam-connect: Internal Server Error ("Head "https://ghcr.io/v2/seamapi/seam-connect/manifests/latest": unauthorized")`

Am I missing any step? Do I need to have permissions for the org in order to pull that image?

**Comment by sybohy** [comment]
unfortunately at the moment, anyone outside Seam can't run the tests locally. We're discussing internally about changing that.
